POST http://localhost:8080/api/v1/subscription
Content-Type: application/json

{
  "userId": 1,
  "productId": 3,
  "subscriptionDate": "2025-05-15T10:00:00",
  "subscriptionExpirationDate": "2026-05-15T10:00:00",
  "subscriptionStatus": "ACTIVE",
  "subscriptionCycleType": "WEEKLY",
  "cycleDetails": [
    "MONDAY",
    "WEDNESDAY"
  ],
  "subscriptionPrice": 1000
}

###
