---
spring:
  datasource:
    url: jdbc:mysql://subpay_mysql:3306/subpay  # jdbc:mysql://localhost:3306/subpay
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
#      name: subscriptionPayJob
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.batch: INFO
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  send-default-pii: true
  debug: false
---

# batch 프로파일 전용 설정
spring:
  profiles: batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
#      name: subscriptionPayJob
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.batch: DEBUG
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  send-default-pii: true
  debug: false
