---
spring:
  datasource:
    url: jdbc:mysql://subpay-db:3306/subpay
    username: root
    password: subpay
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.batch: INFO
---
spring:
  config:
    activate:
      on-profile: batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.batch: DEBUG
