name: CI

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./back

      - name: Build and test with Gradle
        run: ./gradlew build test
        working-directory: ./back

      - name: Publish failure of unit test
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          require_tests: true